name: Deploy Django

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pulling
        run: |
          git config --global --add safe.directory /var/www/html/CI-CD-django
          cd /var/www/html/CI-CD-django
          git pull origin main

      - name: Installing Requirements
        run: |
          cd /var/www/html/CI-CD-django
          venv/bin/pip install -r requirements.txt

      - name: Migrating
        run: |
          cd /var/www/html/CI-CD-django
          venv/bin/python manage.py migrate --no-input

      - name: CollectStatic
        run: |
          cd /var/www/html/CI-CD-django
          venv/bin/python manage.py collectstatic --no-input

      - name: Restarting Gunicorn1 Service
        run: |
          sudo systemctl restart gunicorn1.service

      - name: Reloading Nginx
        run: |
          sudo systemctl reload nginx