name: Deploy Django

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull and deploy
        run: |
          git config --global --add safe.directory /var/www/html/CI-CD-django
          cd /var/www/html/CI-CD-django
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate --no-input
          python manage.py collectstatic --no-input
          sudo systemctl restart gunicorn1.service
          sudo systemctl reload nginx
